### ISSUE TITLE
Last Repository Syncs Indefinitely

### ISSUE THREAD

**Issue by Joomsy** [NeoApplications/Neo-Store#404]
With this new update, the connection to the last repository that's subscribed to will get stuck during a sync. The notification says "Connecting..." indefinitely, and the sync has to be canceled. I at first thought it was just a bad repository, but after unsubscribing, the problem moved onto the next one in the list. Running on a Pixel 7 Pro with stock A13.

![Screenshot_20230124-204351](https://user-images.githubusercontent.com/103767404/214469328-e04e430e-b6b2-4224-808d-68bf476c9b19.png)

**Comment by rjm831** [comment]
Same problem.  Reverted to an older version temporarily.

**Comment by rjm831** [comment]
Same problem.  Reverted to an older version temporarily.

**Comment by wizard-28** [comment]
Same issue here, but for me, it's stuck on "Saving details"

**Comment by wizard-28** [comment]
Same issue here, but for me, it's stuck on "Saving details"

**Comment by machiav3lli** [comment]
Not really stuck syncing, it's just that the notification is not cleared (service unbound).

**Comment by Joomsy** [comment]
> Not really stuck syncing, it's just that the notification is not cleared (service unbound).

Ah, I suppose you're right. You'll have to forgive me, as I wasn't really sure what to title this. List views are updating with new stuff, though, so syncing is indeed working.

**Comment by MatthijsMarco** [comment]
Is there a short term solution to this issue?

**Comment by machiav3lli** [comment]
Just swipe the notification away. This should be fixed in the next stable release, but till then there'll be couple of test builds.

**Comment by MatthijsMarco** [comment]
Maybe Samsung phones handle this differently then, because mine can't be swiped away. Guess I'll just wait and disable the notification for syncing. Thank you!

**Comment by Joomsy** [comment]
> Maybe Samsung phones handle this differently then, because mine can't be swiped away. Guess I'll just wait and disable the notification for syncing. Thank you!

No, I can't swipe it away on my Pixel, either. If you hit "Cancel" on the notification, you can make it go away, and repositories should still be synced.

**Comment by rjm831** [comment]
Yes.  Problem went away for me with the last two updates.

**Comment by knobhead** [comment]
Hi, for me this problem persists with 0.9.15 (Fairhone 3 with LineageOS 19.1) 😥

**Comment by machiav3lli** [comment]
Should have been fixed on the latest alpha (get it from the community groups or TG channel) and report back.

**Comment by Baerbeisser** [comment]
Same here, though with no progress bar.
