### ISSUE TITLE
[Bug] NeoStore Struggles to Update or Install

### ISSUE THREAD

**Issue by liam-clink** [NeoApplications/Neo-Store#721]
### Guidelines

- [x] I have searched the issue tracker for [open](https://github.com/NeoApplications/Neo-Store/issues) and [closed](https://github.com/NeoApplications/Neo-Store/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [x] I'm on the latest version.
- [x] I'm not using a test build (alpha/beta/release-candidate).
- [x] This issue contains only one bug.

### Describe the bug

When I first got neostore, it worked properly, but after a few months, it will download apps and updates, and then won't actually install the apk. I first thought it was that I was trying to install too many updates at once, but this happens even when I try to install one at a time. I'm still able to easily install APKs that I download from a browser or Aurora or F-Droid just fine, so this is specific to NeoStore. I have tried deleting all downloaded APKs  in NeoStore and trying again, and this doesn't help. Installing new apps is also a struggle. If I wait several minutes repeatedly tapping to install, eventually it will sometimes actually install the APK, but this is ridiculous to have to do. 

### Expected Behavior

I click update all and all updates are downloaded and installed without any further input.

### Neo Store's Version

1.0.8

### Installation Source

Official F-Droid repo

### Relevant information

- Device: 8 Pro
- Android Version: 15
- ROM: (AOSP, CalyxOS, MIUI, GOS...) GrapheneOS
- Disabled battery optimization for Neo Store? Yes
- What is your selected installer? Default Session Installer

**Comment by machiav3lli** [comment]
There seems to be a conflict/issue with NS on GOS, as this is not the first issue (#707) or report (in the community groups) of specifically GOS users.

As some user proposed today in the group, using another installers (e.g. App Manager or Root) seems to work. Furthermore as another user mentions in #707 installing NS from GH helped in downloads, but I guess this is not the same as your issue.

**Comment by chrostino** [comment]
I have essentially the same issue, apps/updates get downloaded fine, but then they sit there for a bit of time (5-10 minutes) before getting installed (no need to repeatedly tap on install, sometimes I even just close the app and come back some time later to find the installs done). The difference is I am not on GrapheneOS and also I am using the root installer. I also tried with and without App Manager but it didn't seem to make a difference

**Comment by cyb3rko** [comment]
Same issues, but on stock Android 15 on Pixel 7 Pro

**Comment by gbakeman** [comment]
I'm sorry to say that I've also experienced this issue, OxygenOS (Android 9). No matter the installer mode, Neo Store has been struggling with launching installers. The default Session installer was the only one that remotely worked (and usually requires tapping install multiple times). I can report however that Droid-ify is working flawlessly.

**Comment by Daedalus007** [comment]
I realize I'm a month later but as of v1.0.9 the update/download/install process gets extremely delayed (often just hanging/stuck on syncing repositories) if you have more than what appears to be ~15 repositories active.  Either increase the limit or put a warning that activating more than X repositories will cause issues.

**Comment by chrostino** [comment]
you are right, I never noticed it was caused by a high number of active repositories. Keeping below 15 is making things work much better

**Comment by Daedalus007** [comment]
Doing some preliminary testing it seems adding 20 or more repositories triggers the constant crashing/updating/freezing issues with Neo Store.  None of the repositories end up updating and it ends up stuck in an endless forever-loop while updating/syncing repositories.  I agree that 15 or less is a safe number but this should be clearly disclosed somewhere in the app.

**Comment by Daedalus007** [comment]
I won't be the kind to demand a bugfix or a change or anything.  What I will do is ask to have this 'under 15 repositories' limit displayed somewhere in the app with a warning that going higher is unsupported and may lead to crashes/issues.

**Comment by machiav3lli** [comment]
It's not about the number of active repositories (I use 25+ repos) rather what repositories are active. Usually archive repos and similarly structured ones can be pretty problematic. For example the repos Frostnerd & Aniyomi were causing crashes and other issues couple of months ago, while the MicroG is having issues currently with their server. Also the current 1.1.0-beta (provided in the community groups) build should avoid many of such crashes, delays etc…

**Comment by Daedalus007** [comment]
Mind providing a list of the problematic repos so those of us who aren't on a beta build can avoid them?
Your consideration would be greatly appreciated.
I also don't see any public beta builds.  I'm sure myself and many others would appreciate being pointed in the direction of those builds.  Thanks!

**Comment by machiav3lli** [comment]
It's a moving target with sometimes user-specific issues (e.g. region/VPN/TOR, cpu arch etc..). For example Frostnerd is afaik is still corrupted, but Aniyomi not anymore, while microg repo is facing server issues... there's from time to time also issues discoverrd and fixed in the fdroid server that not all repos apply timely...

**Comment by Daedalus007** [comment]
> It's a moving target with sometimes user-specific issues (e.g. region/VPN/TOR, cpu arch etc..). For example Frostnerd is afaik is still corrupted, but Aniyomi not anymore, while microg repo is facing server issues... there's from time to time also issues discoverrd and fixed in the fdroid server that not all repos apply timely...

Would be nice if you provided a link/method to the beta build instead of completely ignoring my request.  You mentioned the beta build earlier and that this issue was fixed in such build but there's no information anywhere (easily accessible info) on where/how to obtain said build.

**Comment by machiav3lli** [comment]
@Daedalus007 ah sorry, I thought it was clearly written in the README that test builds are provided on the community groups (on [TG](https://t.me/neo_android_store) or [Matrix](https://matrix.to/#/#neo-store:matrix.org)).

**Comment by Daedalus007** [comment]
Not sure why the builds aren't available as beta on Github directly so we can inspect what was changed and how it was changed.  I'll hold off on random beta builds until I can inspect the source code myself.  I'll wait for the next stable update.

Update: Newest v1.1.0 version fixes this issue.  This can be closed as resolved.

**Comment by machiav3lli** [comment]
I don't know were these assumptions come from, but before rolling out such lies maybe you should check it for yourself: test builds are tagged in the repo and built from that code 1:1.

Test builds are provided only on the community groups to avoid ambigious reporting and spamming from users who are not aware what "test builds" entail.

**Comment by eclairevoyant** [comment]
> I realize I'm a month later but as of v1.0.9 the update/download/install process gets extremely delayed (often just hanging/stuck on syncing repositories) if you have more than what appears to be ~15 repositories active. Either increase the limit or put a warning that activating more than X repositories will cause issues.

I doubt it has much to do with a repo limit or using GOS. I have four repos active on a stock ROM and still face this. Basically the same as this issue / #255, #622, #707, #710, etc.

**Comment by gbakeman** [comment]
A massive update with loads of bugfixes was just released (1.1.0), has anyone had a chance to test yet to see if it improves package installation?

**Comment by Daedalus007** [comment]
> A massive update with loads of bugfixes was just released (1.1.0), has anyone had a chance to test yet to see if it improves package installation?

Yes it fixes it for me, as per my prior post above.

> Update: Newest v1.1.0 version fixes this issue. This can be closed as resolved.

**Comment by FBachofner** [comment]
> > A massive update with loads of bugfixes was just released (1.1.0), has anyone had a chance to test yet to see if it improves package installation?
> 
> Yes it fixes it for me, as per my prior post above.
> 
> > Update: Newest v1.1.0 version fixes this issue. This can be closed as resolved.


@machiav3lli please note my experience (I don't have rights to reopen this):


Two days ago I worked on a phone where this was _definitely_ still an issue (using NeoStore 1.1.0).  The phone is a Xiaomi Redmi Note 10Pro (so *not* the phones previously referenced as often "problematic" ) operating on CrDroid 10.x and then updated to 11.7 to specifically attempt to address _this_ (NeoStore) issue.

The ONLY thing which worked is @monospacedmagic 's recommendation to [turn off "System's download manager"](https://github.com/NeoApplications/Neo-Store/issues/707#issuecomment-2743265980) so **thanks** for that hint.

Unfortunately, the phone is now back with its user, so I can not comment on whether NeoStore 1.1.1 (released yesterday) definitively fixes the issue.

**Comment by machiav3lli** [comment]
@FBachofner Yeah, seems that some ROMs have an issue with the system download manager (maybe omitting it fully or playing with its APIs?) and can confirm newer CrDroid versions to have exactly this issue (reproducible on both sweet/RedmiNote10Pro and cepheus/MI9). So since couple of versions the default is back to using NS's own downloader, after fixing some performance issue concerning it.

**Comment by nv4** [comment]
> I don't know were these assumptions come from, but before rolling out such lies maybe you should check it for yourself: test builds are tagged in the repo and built from that code 1:1.
> 
> Test builds are provided only on the community groups to avoid ambigious reporting and spamming from users who are not aware what "test builds" entail.

Just fix the app lil bro 🥱🥱
